### ISSUE TITLE
Support callbacks

### ISSUE THREAD

**Issue by HolyMeekrob** [HolyMeekrob/trello-yello#1]
Right now everything is returned as a Promise. There should be an option for callbacks, otherwise return a Promise.

**Comment by HolyMeekrob** [comment]
Done. Bluebird made this easy.

**Comment by johnpattison** [comment]
How would you determine the success/failure of something like the following without a callback? 

```
trelloService.getCard('1234567890').addComment({ comment: 'some comment.' }); 
```

If I pass in a invalid ID, I get an unhanded error:

```
Unhandled rejection Error: Error sending data to Trello: invalid id
```

**Comment by HolyMeekrob** [comment]
@jpattisoninc `addComment()`, like all other actions, returns a Promise. You can handle the error by adding a catch clause to the end of your Promise handling. See documentation and examples [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch)
